name: YourEvent
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  flutter_svg: ^2.0.10+1
  cloud_firestore: ^4.17.5
  intl: ^0.19.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


fonts:
  - family: Montserrat
  - asset: \assets\fonts\Montserrat-Bold.ttf
    style: Bold
  - family: PTSans
  - asset:  \assets\fonts\PTSans-Bold.ttf
    style: Bold



flutter:
  uses-material-design: true
  assets:
    - assets/images/

