// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPbQu4IlYlXtiy0qnYyoa4klIFaEVX60k',
    appId: '1:794874347189:web:9bad5b38d4de9bba5348fc',
    messagingSenderId: '794874347189',
    projectId: 'yourevent123321',
    authDomain: 'yourevent123321.firebaseapp.com',
    storageBucket: 'yourevent123321.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJrJS6EC09ktiksyX8OECLZBgUOX5e7JY',
    appId: '1:794874347189:android:1bac9809e15512775348fc',
    messagingSenderId: '794874347189',
    projectId: 'yourevent123321',
    storageBucket: 'yourevent123321.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDtoyihM6TCEFeMmrkevYevq8OPKv__5I',
    appId: '1:794874347189:ios:ff9047f5c914525f5348fc',
    messagingSenderId: '794874347189',
    projectId: 'yourevent123321',
    storageBucket: 'yourevent123321.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDtoyihM6TCEFeMmrkevYevq8OPKv__5I',
    appId: '1:794874347189:ios:ff9047f5c914525f5348fc',
    messagingSenderId: '794874347189',
    projectId: 'yourevent123321',
    storageBucket: 'yourevent123321.appspot.com',
    iosBundleId: 'com.example.newproject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPbQu4IlYlXtiy0qnYyoa4klIFaEVX60k',
    appId: '1:794874347189:web:f671054b276a2a7e5348fc',
    messagingSenderId: '794874347189',
    projectId: 'yourevent123321',
    authDomain: 'yourevent123321.firebaseapp.com',
    storageBucket: 'yourevent123321.appspot.com',
  );
}
